#!/bin/sh

dayanddate () {
	LC_TIME="en_US.UTF-8" date '+%G. %B. %e, %A'
}

battery () {
	~/.scripts/battery
}
wifi () {
	~/.scripts/wifi
}
timedate () {
	date '+%I:%M:%S %p'
}

while :; do
	xsetroot -name "$(dayanddate)"";""$(battery)""$(wifi)"" $(timedate)"
	sleep 1
done
