#!/bin/sh

BAT=/sys/class/power_supply/BAT0/capacity

if [ ! -f "$BAT" ]; then
    exit
fi

charging_status=$(grep -m 1 'POWER_SUPPLY_STATUS' /sys/class/power_supply/BAT0/uevent | awk -F= '{print $2}')

if [ "$charging_status" = "Charging" ]; then
    echo "$(cat $BAT)% 󰂄 "
else
    capacity=$(cat $BAT)
    case $capacity in
        100|9[0-9]|8[0-9]) echo "$capacity%  " ;;
        7[0-9]|6[0-9])     echo "$capacity%  " ;;
        5[0-9]|4[0-9])     echo "$capacity%  " ;;
        3[0-9]|2[0-9])     echo "$capacity%  " ;;
        *)                 echo "$capacity%  " ;;
    esac
fi
